<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Low-code UI to keep everyone, tech or b_bd4e50</name>
   <tag></tag>
   <elementGuidId>b457e894-bd1d-4413-a195-3b1c30d26907</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hs_cos_wrapper_module_72124141929']/div/div/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>760b4171-c871-4b62-b066-2c4a30b3a55b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feature_text</value>
      <webElementGuid>13f2ebed-a7a9-4585-a9c3-3d2a9b27bfa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Low-code UI to keep everyone, tech or business, in the loop</value>
      <webElementGuid>1b7cf113-dc89-48b8-8adb-460c57a8424d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hs_cos_wrapper_module_72124141929&quot;)/div[@class=&quot;hero_section&quot;]/div[@class=&quot;main_content&quot;]/div[@class=&quot;features&quot;]/div[@class=&quot;feature_item&quot;]/div[@class=&quot;feature_text&quot;]</value>
      <webElementGuid>b26f019a-9fbc-4663-88da-22e8d7e01acb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hs_cos_wrapper_module_72124141929']/div/div/div/div[3]/div</value>
      <webElementGuid>feef1ca8-7f0e-47ee-9be7-f40da06355b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Centralized workflows to focus on software that wins'])[1]/following::div[2]</value>
      <webElementGuid>1b82a18e-a2af-4de0-847f-0c1cc552ea20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visibility throughout the test pipeline'])[1]/following::div[4]</value>
      <webElementGuid>d10b4394-62f1-407d-bcf4-02c59d92dd31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Out-of-the-box fit for any ALM, CI tools, and system'])[1]/preceding::div[1]</value>
      <webElementGuid>6048946d-59d9-44b1-b26a-d32cf92bf375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enterprises'])[1]/preceding::div[16]</value>
      <webElementGuid>ceec75b0-73b2-4748-b81a-f26732ded287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Low-code UI to keep everyone, tech or business, in the loop']/parent::*</value>
      <webElementGuid>a3fdd977-8552-400d-b43c-09e5f11487db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]/div</value>
      <webElementGuid>ab40b723-892b-4775-9f5d-0f72ca3743d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Low-code UI to keep everyone, tech or business, in the loop' or . = 'Low-code UI to keep everyone, tech or business, in the loop')]</value>
      <webElementGuid>a3319479-1803-471f-86c1-e37c83d401a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
